/*
 * Snapview6 API
 * Official API available to Snapview customers
 *
 * OpenAPI spec version: v1
 * Contact: support@snapview.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.snapview.api.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Container class for model binding of methods CreateSession and EditSession
 */
@ApiModel(description = "Container class for model binding of methods CreateSession and EditSession")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T09:48:31.039+02:00")
public class AccountRequestBody {
  @SerializedName("authentication")
  private Authentication authentication = null;

  @SerializedName("joinsessionUrl")
  private String joinsessionUrl = null;

  public AccountRequestBody authentication(Authentication authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Authentication information
   * @return authentication
  **/
  @ApiModelProperty(required = true, value = "Authentication information")
  public Authentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(Authentication authentication) {
    this.authentication = authentication;
  }

  public AccountRequestBody joinsessionUrl(String joinsessionUrl) {
    this.joinsessionUrl = joinsessionUrl;
    return this;
  }

   /**
   * Custom Joinsession url
   * @return joinsessionUrl
  **/
  @ApiModelProperty(value = "Custom Joinsession url")
  public String getJoinsessionUrl() {
    return joinsessionUrl;
  }

  public void setJoinsessionUrl(String joinsessionUrl) {
    this.joinsessionUrl = joinsessionUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountRequestBody accountRequestBody = (AccountRequestBody) o;
    return Objects.equals(this.authentication, accountRequestBody.authentication) &&
        Objects.equals(this.joinsessionUrl, accountRequestBody.joinsessionUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authentication, joinsessionUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountRequestBody {\n");

    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    joinsessionUrl: ").append(toIndentedString(joinsessionUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

