/*
 * Snapview6 API
 * Official API available to Snapview customers
 *
 * OpenAPI spec version: v1
 * Contact: support@snapview.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.snapview.api.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Class to manage users&#39; communication channels.              Currently only Application Sharing is possible.
 */
@ApiModel(description = "Class to manage users' communication channels.              Currently only Application Sharing is possible.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T09:48:31.039+02:00")
public class CommunicationChannels {
  @SerializedName("applicationSharingActive")
  private Boolean applicationSharingActive = null;

  @SerializedName("applicationSharingDefault")
  private Boolean applicationSharingDefault = null;

  @SerializedName("videoActive")
  private Boolean videoActive = null;

  @SerializedName("videoDefault")
  private Boolean videoDefault = null;

  @SerializedName("audioActive")
  private Boolean audioActive = null;

  @SerializedName("audioDefault")
  private Boolean audioDefault = null;

  @SerializedName("eSignatureActive")
  private Boolean eSignatureActive = null;

  @SerializedName("eSignatureDefault")
  private Boolean eSignatureDefault = null;

  @SerializedName("eSignatureDemoActive")
  private Boolean eSignatureDemoActive = null;

  @SerializedName("eSignatureDemoDefault")
  private Boolean eSignatureDemoDefault = null;

  public CommunicationChannels applicationSharingActive(Boolean applicationSharingActive) {
    this.applicationSharingActive = applicationSharingActive;
    return this;
  }

   /**
   * Application Sharing active flag
   * @return applicationSharingActive
  **/
  @ApiModelProperty(value = "Application Sharing active flag")
  public Boolean isApplicationSharingActive() {
    return applicationSharingActive;
  }

  public void setApplicationSharingActive(Boolean applicationSharingActive) {
    this.applicationSharingActive = applicationSharingActive;
  }

  public CommunicationChannels applicationSharingDefault(Boolean applicationSharingDefault) {
    this.applicationSharingDefault = applicationSharingDefault;
    return this;
  }

   /**
   * Application Sharing defualt flag
   * @return applicationSharingDefault
  **/
  @ApiModelProperty(value = "Application Sharing defualt flag")
  public Boolean isApplicationSharingDefault() {
    return applicationSharingDefault;
  }

  public void setApplicationSharingDefault(Boolean applicationSharingDefault) {
    this.applicationSharingDefault = applicationSharingDefault;
  }

  public CommunicationChannels videoActive(Boolean videoActive) {
    this.videoActive = videoActive;
    return this;
  }

   /**
   * Video active flag
   * @return videoActive
  **/
  @ApiModelProperty(value = "Video active flag")
  public Boolean isVideoActive() {
    return videoActive;
  }

  public void setVideoActive(Boolean videoActive) {
    this.videoActive = videoActive;
  }

  public CommunicationChannels videoDefault(Boolean videoDefault) {
    this.videoDefault = videoDefault;
    return this;
  }

   /**
   * Video defualt flag
   * @return videoDefault
  **/
  @ApiModelProperty(value = "Video defualt flag")
  public Boolean isVideoDefault() {
    return videoDefault;
  }

  public void setVideoDefault(Boolean videoDefault) {
    this.videoDefault = videoDefault;
  }

  public CommunicationChannels audioActive(Boolean audioActive) {
    this.audioActive = audioActive;
    return this;
  }

   /**
   * Audio active flag
   * @return audioActive
  **/
  @ApiModelProperty(value = "Audio active flag")
  public Boolean isAudioActive() {
    return audioActive;
  }

  public void setAudioActive(Boolean audioActive) {
    this.audioActive = audioActive;
  }

  public CommunicationChannels audioDefault(Boolean audioDefault) {
    this.audioDefault = audioDefault;
    return this;
  }

   /**
   * Audio defualt flag
   * @return audioDefault
  **/
  @ApiModelProperty(value = "Audio defualt flag")
  public Boolean isAudioDefault() {
    return audioDefault;
  }

  public void setAudioDefault(Boolean audioDefault) {
    this.audioDefault = audioDefault;
  }

  public CommunicationChannels eSignatureActive(Boolean eSignatureActive) {
    this.eSignatureActive = eSignatureActive;
    return this;
  }

   /**
   * ESign active flag
   * @return eSignatureActive
  **/
  @ApiModelProperty(value = "ESign active flag")
  public Boolean isESignatureActive() {
    return eSignatureActive;
  }

  public void setESignatureActive(Boolean eSignatureActive) {
    this.eSignatureActive = eSignatureActive;
  }

  public CommunicationChannels eSignatureDefault(Boolean eSignatureDefault) {
    this.eSignatureDefault = eSignatureDefault;
    return this;
  }

   /**
   * ESign defualt flag
   * @return eSignatureDefault
  **/
  @ApiModelProperty(value = "ESign defualt flag")
  public Boolean isESignatureDefault() {
    return eSignatureDefault;
  }

  public void setESignatureDefault(Boolean eSignatureDefault) {
    this.eSignatureDefault = eSignatureDefault;
  }

  public CommunicationChannels eSignatureDemoActive(Boolean eSignatureDemoActive) {
    this.eSignatureDemoActive = eSignatureDemoActive;
    return this;
  }

   /**
   * ESignDemo active flag
   * @return eSignatureDemoActive
  **/
  @ApiModelProperty(value = "ESignDemo active flag")
  public Boolean isESignatureDemoActive() {
    return eSignatureDemoActive;
  }

  public void setESignatureDemoActive(Boolean eSignatureDemoActive) {
    this.eSignatureDemoActive = eSignatureDemoActive;
  }

  public CommunicationChannels eSignatureDemoDefault(Boolean eSignatureDemoDefault) {
    this.eSignatureDemoDefault = eSignatureDemoDefault;
    return this;
  }

   /**
   * ESignDemo defualt flag
   * @return eSignatureDemoDefault
  **/
  @ApiModelProperty(value = "ESignDemo defualt flag")
  public Boolean isESignatureDemoDefault() {
    return eSignatureDemoDefault;
  }

  public void setESignatureDemoDefault(Boolean eSignatureDemoDefault) {
    this.eSignatureDemoDefault = eSignatureDemoDefault;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunicationChannels communicationChannels = (CommunicationChannels) o;
    return Objects.equals(this.applicationSharingActive, communicationChannels.applicationSharingActive) &&
        Objects.equals(this.applicationSharingDefault, communicationChannels.applicationSharingDefault) &&
        Objects.equals(this.videoActive, communicationChannels.videoActive) &&
        Objects.equals(this.videoDefault, communicationChannels.videoDefault) &&
        Objects.equals(this.audioActive, communicationChannels.audioActive) &&
        Objects.equals(this.audioDefault, communicationChannels.audioDefault) &&
        Objects.equals(this.eSignatureActive, communicationChannels.eSignatureActive) &&
        Objects.equals(this.eSignatureDefault, communicationChannels.eSignatureDefault) &&
        Objects.equals(this.eSignatureDemoActive, communicationChannels.eSignatureDemoActive) &&
        Objects.equals(this.eSignatureDemoDefault, communicationChannels.eSignatureDemoDefault);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationSharingActive, applicationSharingDefault, videoActive, videoDefault, audioActive, audioDefault, eSignatureActive, eSignatureDefault, eSignatureDemoActive, eSignatureDemoDefault);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunicationChannels {\n");

    sb.append("    applicationSharingActive: ").append(toIndentedString(applicationSharingActive)).append("\n");
    sb.append("    applicationSharingDefault: ").append(toIndentedString(applicationSharingDefault)).append("\n");
    sb.append("    videoActive: ").append(toIndentedString(videoActive)).append("\n");
    sb.append("    videoDefault: ").append(toIndentedString(videoDefault)).append("\n");
    sb.append("    audioActive: ").append(toIndentedString(audioActive)).append("\n");
    sb.append("    audioDefault: ").append(toIndentedString(audioDefault)).append("\n");
    sb.append("    eSignatureActive: ").append(toIndentedString(eSignatureActive)).append("\n");
    sb.append("    eSignatureDefault: ").append(toIndentedString(eSignatureDefault)).append("\n");
    sb.append("    eSignatureDemoActive: ").append(toIndentedString(eSignatureDemoActive)).append("\n");
    sb.append("    eSignatureDemoDefault: ").append(toIndentedString(eSignatureDemoDefault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

