/*
 * Snapview6 API
 * Official API available to Snapview customers
 *
 * OpenAPI spec version: v1
 * Contact: support@snapview.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.snapview.api.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Container class for model binding of method RenewUserESignatureSession
 */
@ApiModel(description = "Container class for model binding of method RenewUserESignatureSession")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T09:48:31.039+02:00")
public class RenewUserIS2SessionRequestBody {
  @SerializedName("authentication")
  private Authentication authentication = null;

  @SerializedName("demoSystem")
  private Boolean demoSystem = null;

  @SerializedName("eSignatureSession")
  private String eSignatureSession = null;

  @SerializedName("sessionDisplayName")
  private String sessionDisplayName = null;

  public RenewUserIS2SessionRequestBody authentication(Authentication authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Authentication information
   * @return authentication
  **/
  @ApiModelProperty(required = true, value = "Authentication information")
  public Authentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(Authentication authentication) {
    this.authentication = authentication;
  }

  public RenewUserIS2SessionRequestBody demoSystem(Boolean demoSystem) {
    this.demoSystem = demoSystem;
    return this;
  }

   /**
   * indicates whether production or demonstration eSignature system should be queried
   * @return demoSystem
  **/
  @ApiModelProperty(required = true, value = "indicates whether production or demonstration eSignature system should be queried")
  public Boolean isDemoSystem() {
    return demoSystem;
  }

  public void setDemoSystem(Boolean demoSystem) {
    this.demoSystem = demoSystem;
  }

  public RenewUserIS2SessionRequestBody eSignatureSession(String eSignatureSession) {
    this.eSignatureSession = eSignatureSession;
    return this;
  }

   /**
   * sessionid of the to be renewed eSignature system&#39;s session
   * @return eSignatureSession
  **/
  @ApiModelProperty(required = true, value = "sessionid of the to be renewed eSignature system's session")
  public String getESignatureSession() {
    return eSignatureSession;
  }

  public void setESignatureSession(String eSignatureSession) {
    this.eSignatureSession = eSignatureSession;
  }

  public RenewUserIS2SessionRequestBody sessionDisplayName(String sessionDisplayName) {
    this.sessionDisplayName = sessionDisplayName;
    return this;
  }

   /**
   * IS2 system&#39;s session displayname for the the session clone instance
   * @return sessionDisplayName
  **/
  @ApiModelProperty(value = "IS2 system's session displayname for the the session clone instance")
  public String getSessionDisplayName() {
    return sessionDisplayName;
  }

  public void setSessionDisplayName(String sessionDisplayName) {
    this.sessionDisplayName = sessionDisplayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RenewUserIS2SessionRequestBody renewUserIS2SessionRequestBody = (RenewUserIS2SessionRequestBody) o;
    return Objects.equals(this.authentication, renewUserIS2SessionRequestBody.authentication) &&
        Objects.equals(this.demoSystem, renewUserIS2SessionRequestBody.demoSystem) &&
        Objects.equals(this.eSignatureSession, renewUserIS2SessionRequestBody.eSignatureSession) &&
        Objects.equals(this.sessionDisplayName, renewUserIS2SessionRequestBody.sessionDisplayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authentication, demoSystem, eSignatureSession, sessionDisplayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RenewUserIS2SessionRequestBody {\n");

    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    demoSystem: ").append(toIndentedString(demoSystem)).append("\n");
    sb.append("    eSignatureSession: ").append(toIndentedString(eSignatureSession)).append("\n");
    sb.append("    sessionDisplayName: ").append(toIndentedString(sessionDisplayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

