/*
 * Snapview6 API
 * Official API available to Snapview customers
 *
 * OpenAPI spec version: v1
 * Contact: support@snapview.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.snapview.api.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Container class for model binding of methods CreateSession and EditSession
 */
@ApiModel(description = "Container class for model binding of methods CreateSession and EditSession")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T09:48:31.039+02:00")
public class SessionRequestBody {
  @SerializedName("authentication")
  private Authentication authentication = null;

  @SerializedName("session")
  private Session session = null;

  public SessionRequestBody authentication(Authentication authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Authentication information
   * @return authentication
  **/
  @ApiModelProperty(required = true, value = "Authentication information")
  public Authentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(Authentication authentication) {
    this.authentication = authentication;
  }

  public SessionRequestBody session(Session session) {
    this.session = session;
    return this;
  }

   /**
   * Session information
   * @return session
  **/
  @ApiModelProperty(required = true, value = "Session information")
  public Session getSession() {
    return session;
  }

  public void setSession(Session session) {
    this.session = session;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionRequestBody sessionRequestBody = (SessionRequestBody) o;
    return Objects.equals(this.authentication, sessionRequestBody.authentication) &&
        Objects.equals(this.session, sessionRequestBody.session);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authentication, session);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionRequestBody {\n");

    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

