/*
 * Snapview6 API
 * Official API available to Snapview customers
 *
 * OpenAPI spec version: v1
 * Contact: support@snapview.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.snapview.api.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Container class for model binding of methods CreateUser and EditUser
 */
@ApiModel(description = "Container class for model binding of methods CreateUser and EditUser")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T09:48:31.039+02:00")
public class UserImageRequestBody {
  @SerializedName("authentication")
  private Authentication authentication = null;

  @SerializedName("base64image")
  private String base64image = null;

  public UserImageRequestBody authentication(Authentication authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Authentication information
   * @return authentication
  **/
  @ApiModelProperty(required = true, value = "Authentication information")
  public Authentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(Authentication authentication) {
    this.authentication = authentication;
  }

  public UserImageRequestBody base64image(String base64image) {
    this.base64image = base64image;
    return this;
  }

   /**
   * The base64 encoded contents of the image file.  Please do not pass a complete URI data string here, which additionally to file contents contains a preamble text, for example like &#39;data:image/png;base64,&#39;.
   * @return base64image
  **/
  @ApiModelProperty(required = true, value = "The base64 encoded contents of the image file.  Please do not pass a complete URI data string here, which additionally to file contents contains a preamble text, for example like 'data:image/png;base64,'.")
  public String getBase64image() {
    return base64image;
  }

  public void setBase64image(String base64image) {
    this.base64image = base64image;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserImageRequestBody userImageRequestBody = (UserImageRequestBody) o;
    return Objects.equals(this.authentication, userImageRequestBody.authentication) &&
        Objects.equals(this.base64image, userImageRequestBody.base64image);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authentication, base64image);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserImageRequestBody {\n");

    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    base64image: ").append(toIndentedString(base64image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

